name: Take Down Cloud Run Deployment

on:
  workflow_dispatch:

jobs:
  take_down:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Bring down deployments
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        for service in $(docker-compose config --services); do
          gcloud run services delete $service --platform managed --region europe-west1 --quiet
        done